### ISSUE TITLE
FP on DRB115

### ISSUE THREAD

**Issue by markbcahill** [coderrect-inc/OpenRace#231] opened 2021-06-23 19:51 UTC
**Describe the bug**
OpenRace detects a data race pair between 65:20 and itself in DRB115.

**Expected behavior**
No data race is detected

**To Reproduce**
Run OpenRace on DRB115

**Additional context**
OpenRace correctly finds a data race on line 66 in DRB115, as expected.

**Comment by BradSwain** [comment] 2021-06-23 20:27
Hi mark, DRB 115 makes use of SIMD, which is a feature we are still working on supporting. (See #118 )

**Comment by BradSwain** [comment] 2021-06-28 15:20
Thanks for reporting the issues mark. Since this one is covered by #118 I am going to mark as closed to prevent confusion.

Duplicate of #118

**Closed by BradSwain** 2021-06-28 15:20 UTC
Labels: bug
